  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Tech"
  weight = 300
  identifier = "tech"
  url = "/tech/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"
