# Default values for logstream-workergroup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

rbac:
  create: true
  apiGroups: 
  - core
  resources:
  - pods
  verbs:
  - get
  - list
  annotations: {}

criblImage:
  repository: cribl/cribl
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "3.3.0"

imagePullSecrets: []
nameOverride: "edge-wg"

config: 
  host: 192.168.68.83
  group: homek8s
  token: criblmaster
  rejectSelfSignedCerts: 0
  healthPort: 9000
  tlsLeader:
    enable: false

deployment: daemonset

env:
  CRIBL_DIST_MODE: managed-edge
  CRIBL_EDGE: 1

podAnnotations: {}


service:
  type: LoadBalancer
  annotations: {}

  ports:
  - name: tcpjson
    port: 10001
    protocol: TCP
  - name: s2s
    port: 9997
    protocol: TCP
  - name: http
    port: 10080
    protocol: TCP
  - name: https
    port: 10081
    protocol: TCP    
  - name: syslog
    port: 5140
    protocol: TCP
  - name: metrics
    port: 8125
    protocol: TCP
  - name: elastic
    port: 9200
    protocol: TCP

resources: 
  limits:
    cpu: 2000m
    memory: 4096Mi
  requests:
    cpu: 1250m
    memory: 256Mi
    
extraVolumeMounts:
  - name: hostroot
    mountPath: /hostfs
    hostPath: /


# autoscaling:
#   enabled: true
#   minReplicas: 2
#   maxReplicas: 10
#   targetCPUUtilizationPercentage: 50
